config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	root to: "home#index"
	
	# get 'items/create'
	# get 'items/index'
	resources :items do
	  get :upvote,on: :member
	  get :expensive, on: :collection
	end    

	get "admin/users_count" => "admin#users_count"      
  
   
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
	has_many :comments,as: :commentable
end

app/models/cart.rb
class Cart < ApplicationRecord
  
  has_many                :positions
  belongs_to              :user
  has_many :items,through: :positions
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true
end

app/models/item.rb
class Item < ApplicationRecord
	validates :price,numericality: {greater_than:0,allow_nil: true}
	validates :name, :description,presence: true

	
	has_many :positions
	has_many :carts,through: :positions

	has_many :comments,as: :commentable
	
    has_and_belongs_to_many :orders
   # attr_acessible :price,:name,:real,:weight,:description
    # after_initialize {}
    # after_save       {}
    # after_create     { category.inc(:item_count,1)}
    # after_update     {}
    # after_destroy    { category.inc(:items_count,-1)}
end

app/models/order.rb
class Order < ApplicationRecord
	# attr_accessible :user, :user_id
  belongs_to :user
  has_and_belongs_to_many :items

  before_save do 
  	raise "no items in order" if items.empty?
  end
  	
  
  def calculate_total
  	write_attribute :total,items.map(&:price).inject(:+)
  end
end

app/models/position.rb
class Position < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

# attr_accessible :login,:email, :password, :password_confirmation, :remember_me
	has_one :cart
	has_many :orders
	has_many :comments
	
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController

  before_filter :check_if_admin
  layout "admin"

  def users_count
  	@users_count = User.count
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

	protect_from_forgery with: :exception

	private

	def render_403
	  render file: "public/403.html", status: 403
	end
	def render_404
	  render file: "public/404.html",status: 404
	end

     def check_if_admin
     # render text:"Access denied",status: 403 unless params[:admin]
     render_403 unless params[:admin]
    end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

	before_filter :find_item, only: [:show,:edit,:update,:destroy,:upvote]
    #before_filter :check_if_admin, only: [:edit,:update,:new,:create,:destroy]
    #before_filter :authenticate_user!
  def index
  	@items = Item
  	@items = @items.where(" price >=?",params[:price_from])      if params[:price_from]
  	@items = @items.where("created_at >= ?",1.day.ago)            if params[:today]
  	@items = @items.where("votes_count >=?",params[:votes_from]) if params[:votes_from]
  	@items = @items.order("votes_count DESC","price")

  end

  def expensive
  	@items = Item.where("price > 1000")
  	render "index"
  end

  def show
    # raise "exception test"
  	unless @item 
  	render text:"Poge not found", status: 404
    end

  end
  
  def new
  	@item = Item.new
  end

  def edit
   
  end

  def create
  	@item = Item.create(item_params)
  	@item.save
  	if @item.errors.empty?
  		redirect_to item_path(@item)
  	else
  		render "new"
  	end
  end

  def update
  	@item.save
  	if 
  		@item.update(item_params)
  		@item.errors.empty?
  		flash[:success] = "Товар обновлён"
  		redirect_to item_path(@item)
  	else
      flash.now[:error] = "Пожалуйста,корректно заполняйте форму"  	  
      render "edit"
  	end
  end

  def destroy
  
  	@item.destroy
  	render json: { success: true}
    ItemMailer.item_destroyed(@item).deliver
  end

def upvote
  @item.increment!(:votes_count)
  redirect_to action: :index
end


  private
    def item_params
      params.require(:item).permit(:name,:price,:description,:weight)
    end

    def find_item
      	@item = Item.where(id: params[:id]).first
      	render_404 unless @item
    end

   
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def urls_to_images(s)
    s.gsub! /\s(http:\/\/.*?\.(png|jpg))\s/,
    '<p><img src="\1"/></p>'
    s.html_safe
  end

  def urls_to_links(s)

   s.gsub! /\s(http:\/\/.*?)\s/,
    '<a href="\1">\1</a>'
    s.html_safe
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/admin/users_count.html.erb
There are <%= @users_count %> on the site.

app/views/items/_form.html.erb
<%= simple_form_for @item do |f| %>

<%= f.input :price %>
<%= f.input :name %>
<%= f.input :description %>
<%= f.input :weight %>

<%= f.button :submit  %>
<% end %>

app/views/items/edit.html.erb
<h1>Обновляем товар</h1>
 

<%= render partial: "form" %>
  

app/views/items/index.html.erb
<h1>Товар</h1>
<table>
    <tr>
        <th>товар</th>
        <th>Название</th>
        <th>Цена</th>
        <th></th>
        <th></th>
    </tr>
    <% @items.each do |i| %>
        <tr>
            <td>
                <%= i.id %>
            </td>
            <td>
                <%= link_to i.name, item_path(i) %>
            </td>
            <td>
                <%= i.price %> руб.</td>
            <td><span class="deleteAction">Удалить</span></td>
            <td>Рейтинг:
                <%= i.votes_count %>,
                    <%= link_to "+",upvote_item_path(i) %>
            </td>
        </tr>
        <% end %>
</table>

app/views/items/new.html.erb
<h1>Создаём новый товар</h1>



  <%= render partial: "form" %>

  

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
  <li><%= @item.price %>руб</li>
  <li><%= urls_to_links(urls_to_images(@item.description))%></li>
  <li><%= t("item.weight")%> <%= @item.weight %>кг</li>

 

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewShop2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="adminPanel">
  	Useful links here...admin
  </div>

    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewShop2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  <p style="color: red"><%= flash[:error] %></p>
  <p style="color: green "><%= flash[:success] %></p>
    <%= yield %>
  </body>
</html>